FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY . .
ENV GOMODCACHE=/app/vendor
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags=consul -o /app/bin/agent ./cmd/agent

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/bin/agent /app/agent
EXPOSE 8081
ENTRYPOINT ["/app/agent"]
