FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY . .
ENV GOMODCACHE=/app/vendor
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags=consul -o /app/bin/controller ./cmd/controller

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/bin/controller /app/controller
EXPOSE 8080
ENTRYPOINT ["/app/controller"]
