FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY . .
ENV GOMODCACHE=/app/vendor
ARG BUILD_VERSION
ARG BUILD_LDFLAGS="-s -w"
RUN apk add --no-cache tzdata && \
    BUILD_VERSION=${BUILD_VERSION:-$(TZ=Asia/Shanghai date +%Y-%m-%d-%H-%M)} && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags=consul -ldflags="${BUILD_LDFLAGS} -X peer-wan/pkg/version.Build=${BUILD_VERSION}" -o /app/bin/controller ./cmd/controller

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/bin/controller /app/controller
EXPOSE 8080
ENTRYPOINT ["/app/controller"]
